name: Build and Push Image
run-name: "Build and Push Image"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-version:
    runs-on: ubuntu-latest
    outputs:
      tagVersion: ${{ steps.createTagVersion.outputs.tagVersion }}
    steps:
      - uses: actions/checkout@v4

      - name: Get branch names
        id: branch_names
        uses: OctopusDeploy/util-actions/current-branch-name@current-branch-name.0.1.0

      - name: Get package.json content
        id: get-package-json
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "json-content<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo `cat ./package.json` >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      - name: Create Tag Version
        run: |
          content=`cat ./package.json`
          goVersion=${{ fromJson(steps.get-package-json.outputs.json-content).version }}
          if [[ "${{steps.branch_names.outputs.branch_name}}" != "main" ]]
            then
            preRelease="-${{steps.branch_names.outputs.branch_name}}-$(date +'%Y%m%d%H%M%S')"
          fi
          tagVersion="$goVersion$preRelease"
          echo "tagVersion=$tagVersion" >> $GITHUB_OUTPUT;
          echo "tagVersion=$tagVersion";
        id: createTagVersion

  build-debug:
    runs-on: ubuntu-latest
    needs: create-version

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_DOCKER_REPO_HOSTNAME }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build and push debug image
        uses: docker/build-push-action@v5
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: "${{ secrets.ARTIFACTORY_DOCKER_REPO_HOSTNAME }}/octopusdeploy/kubernetes-agent-nfs-watchdog:debug-${{ needs.create-version.outputs.tagVersion }}"
          platforms: linux/amd64,linux/arm64
          target: debug

  build-production:
    runs-on: ubuntu-latest
    needs: create-version

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_DOCKER_REPO_HOSTNAME }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/main' && startsWith(github.event.commits[0].message, 'Version Kubernetes Agent NFS Watchdog') }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push for test
        uses: docker/build-push-action@v5
        if: github.event_name == 'pull_request'
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: "${{ secrets.ARTIFACTORY_DOCKER_REPO_HOSTNAME }}/octopusdeploy/kubernetes-agent-nfs-watchdog:${{ needs.create-version.outputs.tagVersion }}"
          platforms: linux/amd64,linux/arm64
          target: production

      # Only push to production if it's a versioning commit
      - name: Build and push for production
        uses: docker/build-push-action@v5
        if: ${{ github.ref == 'refs/heads/main' && startsWith(github.event.commits[0].message, 'Version Kubernetes Agent NFS Watchdog') }}
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: "${{ secrets.ARTIFACTORY_DOCKER_REPO_HOSTNAME }}/octopusdeploy/kubernetes-agent-nfs-watchdog:${{ needs.create-version.outputs.tagVersion }},${{ secrets.ARTIFACTORY_DOCKER_REPO_HOSTNAME }}/octopusdeploy/kubernetes-agent-nfs-watchdog:latest,octopusdeploy/kubernetes-agent-nfs-watchdog:${{ needs.create-version.outputs.tagVersion }},octopusdeploy/kubernetes-agent-nfs-watchdog:latest"
          platforms: linux/amd64,linux/arm64
          target: production